### ISSUE TITLE
Step1 기술스택 및 개발환경 공유

### ISSUE THREAD

**Issue by seungdeok** [fotcamp/tech-blog#2]
# 기술스택
### 배포(github pages, s3, vercel)

<br />

# 개발환경
### 코드 컨벤션(naming, import order, folder)

<br />

# ETC
자유롭게 제안 및 수정 바랍니다:)

**Comment by seungdeok** [comment]
**Eslint**
https://eslint.org/

**Prettier**
https://prettier.io/

**Editorconfig**
https://editorconfig.org/

**NVM**
https://github.com/nvm-sh/nvm

**Stylelint**
https://stylelint.io/

**.gitignore**
https://www.toptal.com/developers/gitignore

**env**
https://developer.mozilla.org/ko/docs/Web/CSS/env

**git hook**
https://git-scm.com/book/ko/v2/Git%EB%A7%9E%EC%B6%A4-Git-Hooks
https://typicode.github.io/husky/

**git issue, pr, commit template**
https://git-scm.com/book/ko/v2/Git%EB%A7%9E%EC%B6%A4-Git-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by widse** [comment]
제안) 
Framework: next
이유)
처음에는 라이러리 react 로만 구현해도 상관 없을 거라 생각 했는데,
블로그의 특성상 검색 노출이 중요하고 정적인 컨텐츠 노출이 많다는 점에서, 
next js로 서버 사이드 렌더링 SEO 최적화 및 정적 생성 (Static Generation)으로 성능 향상이 가능하며
추가로 next js 에 대해 조금이라도 더 알고싶은 바램이 있어 제안 요청합니다!

**Comment by seungdeok** [comment]
## 언어
- typescript

## 패키지매니저(npm, yarn, pnpm)
- [yarn berry v4](https://github.com/yarnpkg/berry)

## 번들러(webpack, vite)
- next default 사용

## Framework & Library(react, next)
- next@latest app router

## Styling(css in js, css)
- [ ] [Chakra UI](https://chakra-ui.com/)  -> SSR 미지원
- [x] [Radix](https://www.radix-ui.com/) -> 결정
- [ ] [NextUI](https://nextui.org/) -> 커뮤니티나 컴포넌트가 아직은 개발 중

## 상태관리
### Client
- [x] zustand(https://www.npmjs.com/package/zustand)
- [ ] recoil(https://www.npmjs.com/package/recoil)

### Server
- [TanStack Query](https://tanstack.com/query/latest)

## 애니메이션
- [x] Framer motion -> 반박불가

## 타입검사
- [x] zod

## 코드 및 구조
- [x] eslint
- [x] prettier
- [ ] stylelint -> UI라이브러리 사용하므로 불필요
- [ ] editorconfig -> 내부 기여자들이 같은 에디터 사용
- [x] nvm

## 호스팅
- [x] EC2
- [ ] Vercel
- [ ] 개인 컴퓨터
- [ ] S3
- [ ] Github Pages
- [ ] AWS Beanstalk

새로운 EC2 instance로 결정
-> DB 사용 가능성과 대시보드 및 관리측면에서 현재 사용하고 있는 EC2 서비스를 사용

## Domain
- 기존에 구입해두었던 도메인의 서브 도메인을 활용 `*.fin-hub.co.kr`
- `tech-blog.fin-hub.co.kr`으로 결정

## Testing(storybook, msw, jest, RTL, cypress, playwright)
- [x] storybook
- 테스팅이 필요한데 추후 결정

## 로깅
- Sentry -> next api webhook -> slack
